"""create_evidently_reports_table

Revision ID: 0facd07496b8
Revises: a3c7e1f9d204
Create Date: 2026-06-15 18:07:10.421631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0facd07496b8'
down_revision: Union[str, Sequence[str], None] = 'a3c7e1f9d204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evidently_reports',
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.Column('report_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_evidently_reports_batch_id'), 'evidently_reports', ['batch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidently_reports_batch_id'), table_name='evidently_reports')
    op.drop_table('evidently_reports')
    # ### end Alembic commands ###
