"""add batch_id column

Revision ID: f8c471ae0648
Revises: 86d418fb4853
Create Date: 2026-06-09 11:57:54.693969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c471ae0648'
down_revision: Union[str, Sequence[str], None] = '86d418fb4853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inferences', sa.Column('batch_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inferences', 'batch_id')
    # ### end Alembic commands ###
